name: clothes_rental_mobile
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7  
  flutter_lints: ^2.0.0
  dio: ^5.3.3  
  awesome_snackbar_content: ^0.1.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true
  
  fonts:
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/Sofia Pro Light VN.otf
          weight: 300
        - asset: assets/fonts/Sofia Pro Regular VN.otf
          weight: 400
        - asset: assets/fonts/Sofia Pro Medium VN.otf
          weight: 500
        - asset: assets/fonts/Sofia Pro SemiBold VN.otf
          weight: 600
        - asset: assets/fonts/Sofia Pro Bold VN.otf
          weight: 700
    - family: Solway
      fonts:
        - asset: assets/fonts/solway/Solway-Bold.ttf
          weight: 700
        - asset: assets/fonts/solway/Solway-Regular.ttf
        - asset: assets/fonts/solway/Solway-Light.ttf      
          weight: 300

